export const COUNTRY_RESOURCES = {
  India: [
    {
      id: "in-livelovelaugh",
      title: "Live Love Laugh Foundation",
      description: "Free mental health and counseling helpline.",
      url: "https://www.thelivulovelaughfoundation.org/helpline",
      category: "Helpline",
      contact: "1800-599-0019",
      tags: ["Helpline", "Free", "Counseling"],
      icon: "phone",
      country: "India",
    },
    {
      id: "in-sneha",
      title: "Sneha",
      description: "Depression helpline.",
      url: "https://snehaindia.org/",
      category: "Helpline",
      contact: "+91 44 24640050",
      tags: ["Depression", "Helpline"],
      icon: "phone",
      country: "India",
    },
    {
      id: "in-icall",
      title: "iCALL",
      description: "Psychosocial helpline.",
      url: "http://icallhelpline.org/",
      category: "Helpline",
      contact: "9152987821",
      tags: ["Helpline", "Psychosocial"],
      icon: "phone",
      country: "India",
    },
    {
      id: "in-mann-talks",
      title: "Mann Talks",
      description: "A confidential helpline for emotional and mental well-being.",
      url: "https://www.manntalks.org/",
      category: "Helpline",
      contact: "8686139139",
      tags: ["Helpline", "Emotional Support"],
      icon: "phone",
      country: "India",
    },
    {
      id: "in-tele-manas",
      title: "Tele-MANAS",
      description: "Government of India's 24x7 free mental health rehabilitation helpline.",
      url: "https://telemanas.mohfw.gov.in/",
      category: "Helpline",
      contact: "14416",
      tags: ["Government", "Helpline", "24x7"],
      icon: "phone",
      country: "India",
    },
  ],
  "United Kingdom": [
    {
      id: "uk-samaritans",
      title: "Samaritans",
      description: "24/7 confidential support for people experiencing feelings of distress or despair.",
      url: "https://www.samaritans.org/",
      category: "Crisis Support",
      contact: "116 123",
      tags: ["Crisis", "24x7", "Helpline"],
      icon: "phone",
      country: "United Kingdom",
    },
    {
      id: "uk-mind",
      title: "Mind",
      description: "Provides advice and support to empower anyone experiencing a mental health problem.",
      url: "https://www.mind.org.uk/",
      category: "Information",
      contact: "0300 123 3393",
      tags: ["Information", "Support"],
      icon: "phone",
      country: "United Kingdom",
    },
    {
      id: "uk-shout",
      title: "Shout",
      description: "24/7 UK crisis text service available for times when people feel they need immediate support.",
      url: "https://giveusashout.org/",
      category: "Crisis Support",
      contact: "Text SHOUT to 85258",
      tags: ["Crisis", "24x7", "Text"],
      icon: "message",
      country: "United Kingdom",
    },
    {
      id: "uk-calm",
      title: "CALM (Campaign Against Living Miserably)",
      description: "Provides a helpline and webchat for those who are feeling down or have hit a wall for any reason.",
      url: "https://www.thecalmzone.net/",
      category: "Helpline",
      contact: "0800 58 58 58",
      tags: ["Helpline", "Webchat"],
      icon: "phone",
      country: "United Kingdom",
    },
  ],
  Canada: [
    {
      id: "ca-crisis-services",
      title: "Crisis Services Canada",
      description: "National network of existing distress, crisis and suicide prevention line services.",
      url: "https://www.crisisservicescanada.ca/en/",
      category: "Crisis Support",
      contact: "1-833-456-4566",
      tags: ["Crisis", "Suicide Prevention", "Helpline"],
      icon: "phone",
      country: "Canada",
    },
    {
      id: "ca-kids-help-phone",
      title: "Kids Help Phone",
      description: "Canada’s only 24/7, national support service offering professional counselling, information and referrals and volunteer-led, text-based support to young people in both English and French.",
      url: "https://kidshelpphone.ca/",
      category: "Youth",
      contact: "1-800-668-6868",
      tags: ["Youth", "24x7", "Counseling"],
      icon: "phone",
      country: "Canada",
    },
    {
      id: "ca-hope-for-wellness",
      title: "Hope for Wellness Helpline",
      description: "Provides immediate mental health counselling and crisis intervention to all Indigenous peoples across Canada.",
      url: "https://www.hopeforwellness.ca/",
      category: "Indigenous Support",
      contact: "1-855-242-3310",
      tags: ["Indigenous", "Counseling", "Crisis"],
      icon: "phone",
      country: "Canada",
    },
  ],
  Australia: [
    {
      id: "au-lifeline",
      title: "Lifeline Australia",
      description: "A national charity providing all Australians experiencing a personal crisis with access to 24 hour crisis support and suicide prevention services.",
      url: "https://www.lifeline.org.au/",
      category: "Crisis Support",
      contact: "13 11 14",
      tags: ["Crisis", "24x7", "Suicide Prevention"],
      icon: "phone",
      country: "Australia",
    },
    {
      id: "au-beyond-blue",
      title: "Beyond Blue",
      description: "Provides information and support to help everyone in Australia achieve their best possible mental health, whatever their age and wherever they live.",
      url: "https://www.beyondblue.org.au/",
      category: "Information",
      contact: "1300 22 4636",
      tags: ["Information", "Support"],
      icon: "phone",
      country: "Australia",
    },
    {
      id: "au-headspace",
      title: "headspace",
      description: "The National Youth Mental Health Foundation providing early intervention mental health services to 12-25 year olds.",
      url: "https://headspace.org.au/",
      category: "Youth",
      contact: "1800 650 890",
      tags: ["Youth", "Early Intervention"],
      icon: "phone",
      country: "Australia",
    },
  ],
  Germany: [
    {
      id: "de-telefonseelsorge",
      title: "TelefonSeelsorge",
      description: "Offers confidential and anonymous counseling 24/7.",
      url: "https://www.telefonseelsorge.de/",
      category: "Helpline",
      contact: "0800 111 0 111",
      tags: ["Helpline", "24x7", "Anonymous"],
      icon: "phone",
      country: "Germany",
    },
    {
      id: "de-krisendienst",
      title: "Berliner Krisendienst",
      description: "Berlin Crisis Service provides fast and professional assistance for psychosocial crises.",
      url: "https://www.berliner-krisendienst.de/",
      category: "Crisis Support",
      contact: "Check website for regional numbers",
      tags: ["Crisis", "Berlin"],
      icon: "phone",
      country: "Germany",
    },
  ],
  France: [
    {
      id: "fr-suicide-ecoute",
      title: "Suicide Écoute",
      description: "24/7 confidential helpline for those considering suicide.",
      url: "http://www.suicide-ecoute.fr/",
      category: "Crisis Support",
      contact: "01 45 39 40 00",
      tags: ["Crisis", "24x7", "Suicide Prevention"],
      icon: "phone",
      country: "France",
    },
    {
      id: "fr-sos-amitie",
      title: "SOS Amitié",
      description: "Emotional support helpline.",
      url: "https://www.sos-amitie.com/",
      category: "Helpline",
      contact: "Check website for regional numbers",
      tags: ["Emotional Support", "Helpline"],
      icon: "phone",
      country: "France",
    },
  ],
  Brazil: [
    {
      id: "br-cvv",
      title: "CVV (Centro de Valorização da Vida)",
      description: "Provides emotional support and suicide prevention, operating 24/7.",
      url: "https://www.cvv.org.br/",
      category: "Crisis Support",
      contact: "188",
      tags: ["Crisis", "24x7", "Suicide Prevention"],
      icon: "phone",
      country: "Brazil",
    },
  ],
  Japan: [
    {
      id: "jp-tell",
      title: "TELL Japan",
      description: "24/7 anonymous and confidential lifeline and counseling services in English.",
      url: "https://telljp.com/",
      category: "Crisis Support",
      contact: "03-5774-0992",
      tags: ["Crisis", "24x7", "English"],
      icon: "phone",
      country: "Japan",
    },
    {
      id: "jp-yorisoi",
      title: "Yorisoi Hotline",
      description: "Free phone counseling available in multiple languages.",
      url: "https://www.since2011.net/yorisoi/",
      category: "Helpline",
      contact: "0120-279-338",
      tags: ["Helpline", "Multilingual"],
      icon: "phone",
      country: "Japan",
    },
  ],
  Russia: [
    {
      id: "ru-helpline",
      title: "Moscow Psychological Aid Service",
      description: "Free and anonymous psychological help.",
      url: "https://msph.ru/",
      category: "Helpline",
      contact: "051",
      tags: ["Helpline", "Free", "Anonymous"],
      icon: "phone",
      country: "Russia",
    },
  ],
  China: [
    {
      id: "cn-lifeline",
      title: "Lifeline China",
      description: "Provides crisis support and emotional support for the English-speaking community in China.",
      url: "https://www.lifelinechina.org/",
      category: "Crisis Support",
      contact: "400 821 1215",
      tags: ["Crisis", "English"],
      icon: "phone",
      country: "China",
    },
  ],
  Pakistan: [
    {
      id: "pk-umang",
      title: "Umang",
      description: "Pakistan's first 24/7 mental health helpline.",
      url: "https://umang.com.pk/",
      category: "Helpline",
      contact: "0311-7786264",
      tags: ["Helpline", "24x7"],
      icon: "phone",
      country: "Pakistan",
    },
    {
      id: "pk-taskeen",
      title: "Taskeen Health Initiative",
      description: "Offers free telephonic mental health support and an AI-powered chatbot.",
      url: "https://www.taskeen.org/",
      category: "Helpline",
      contact: "0311-1TASKEE(827533)",
      tags: ["Helpline", "AI Chatbot", "Free"],
      icon: "phone",
      country: "Pakistan",
    },
  ],
};